# Generated by Django 3.0.10 on 2021-01-31 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0002_todo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='TodoList',
        ),
    ]
