# Generated by Django 3.0.10 on 2021-01-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0003_auto_20210131_1141'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TodoList',
        ),
    ]
