# Generated by Django 3.1.5 on 2021-02-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0005_todolist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='text',
            field=models.CharField(max_length=350),
        ),
    ]
