# Generated by Django 3.1.5 on 2021-02-13 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0006_auto_20210202_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
