# Generated by Django 3.1.5 on 2021-02-14 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0008_auto_20210213_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='priority',
        ),
        migrations.AddField(
            model_name='task',
            name='prior',
            field=models.BooleanField(default=False),
        ),
    ]
