# Generated by Django 3.1.5 on 2021-02-17 16:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0010_auto_20210217_1803'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 17, 16, 14, 27, 176377, tzinfo=utc)),
        ),
    ]
