# Generated by Django 3.1.5 on 2021-02-17 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0011_task_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(editable=False),
        ),
    ]
