# Generated by Django 3.1.5 on 2021-02-17 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0014_auto_20210217_1840'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='modified',
        ),
    ]
