# Generated by Django 3.1.5 on 2021-02-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0015_remove_task_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
