# Generated by Django 3.1.5 on 2021-02-27 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doVision', '0018_auto_20210222_2217'),
        ('doVision', '0018_auto_20210227_1044'),
    ]

    operations = [
    ]
